server:
  applicationConnectors:
  - type: http
    port: 7777
  adminConnectors:
  - type: http
    port: 7778

# Redis
redisURL: localhost

# Security
tokenHeaderPrefix: Bearer
tokenQueryParamKey: key