server:
  applicationConnectors:
  - type: http
    port: 7777
  adminConnectors:
  - type: http
    port: 7778

# Karma
userInitialKarma: 1
#KarmaIncrementInterval = 3600
#KarmaIncrementAmount = 1
#NewsDownvoteMinKarma = 30
#NewsDownvoteKarmaCost = 6
#NewsUpvoteMinKarma = 1
#NewsUpvoteKarmaCost = 1
#NewsUpvoteKarmaTransfered = 1
#KarmaIncrementComment = 1